
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;


public class User extends javax.swing.JFrame {

    Map<String,Integer> userOrders = new LinkedHashMap<String,Integer>();
    public User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        black_checked = new javax.swing.JCheckBox();
        softChecked = new javax.swing.JCheckBox();
        LightChecked = new javax.swing.JCheckBox();
        DoubleChecked = new javax.swing.JCheckBox();
        Chocolate_checked = new javax.swing.JCheckBox();
        cheeseChecked = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu");

        black_checked.setText("Black Coffee --10$");

        softChecked.setText("Soft Coffee -- 7$");

        LightChecked.setText("Light Coffee --13$");

        DoubleChecked.setText("Double Coffee --11$");

        Chocolate_checked.setText("Chocolota --5$");

        cheeseChecked.setText("Cheese cake --15$");

        jButton1.setText("Show order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cheeseChecked)
                    .addComponent(Chocolate_checked)
                    .addComponent(DoubleChecked, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LightChecked)
                    .addComponent(softChecked)
                    .addComponent(black_checked)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(black_checked)
                .addGap(18, 18, 18)
                .addComponent(softChecked)
                .addGap(18, 18, 18)
                .addComponent(LightChecked)
                .addGap(18, 18, 18)
                .addComponent(DoubleChecked)
                .addGap(18, 18, 18)
                .addComponent(Chocolate_checked)
                .addGap(18, 18, 18)
                .addComponent(cheeseChecked)
                .addGap(89, 89, 89)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(black_checked.isSelected()){
            userOrders.put("Black Coffee", 10);
        }else{
            userOrders.remove("Black Coffee");
        }
        if(DoubleChecked.isSelected()){
            userOrders.put("Double Coffe", 11);
        }else{
            userOrders.remove("Double Coffee");
        }
        if(LightChecked.isSelected()){
            userOrders.put("Light Coffee", 13);
        }else{
            userOrders.remove("Light Coffee");
        }
        if(cheeseChecked.isSelected()){
            userOrders.put("Cheese Cake", 15);
        }else{
            userOrders.remove("Cheese Cake");
        }
        if(softChecked.isSelected()){
            userOrders.put("Soft Coffee", 7);
        }else{
            userOrders.remove("Soft Coffe");
        }
        if(Chocolate_checked.isSelected()){
            userOrders.put("Chocolate",5);
        }else{
            userOrders.remove("Chocolate");
        }
        showOrders();
    }//GEN-LAST:event_jButton1ActionPerformed
  public void showOrders(){
      String message = "";
      int Ordertotal=0;
      if(userOrders.isEmpty()){
          message =" User order is empty!";
      }
      else{
          message += "Orders\n";
          for(Map.Entry<String,Integer> entry: userOrders.entrySet()){
              message += entry.getKey() + "\n";
              Ordertotal += entry.getValue();
              
          }
          message += "total: " + Ordertotal;
          
      }
      JOptionPane.showMessageDialog(this, message);
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Chocolate_checked;
    private javax.swing.JCheckBox DoubleChecked;
    private javax.swing.JCheckBox LightChecked;
    private javax.swing.JCheckBox black_checked;
    private javax.swing.JCheckBox cheeseChecked;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox softChecked;
    // End of variables declaration//GEN-END:variables
}
